const MainFooter = () => {
    return (   
    <div className="px-6 pb-2 pt-8 mt-8 w-full uppercase text-neutral-500 tracking-wide font-semibold border-t-4 border-double border-dark">
        <div className="text-xs leading-tight w-full flex flex-wrap gap-2">
         <p> 
            <span className="italic font-bold text-neutral-600">@The Cinefile Blog {new Date().getFullYear()}</span> is Designed, developed and deployed by 
            <a className="italic hover:underline text-crimson" href="#">@sonicakes</a>.
            </p> 
          <p>All critique is
          subjective and a personal opinion of the author.</p>
         <p>Film metadata from 
            <a className="italic hover:underline text-crimson" href="https://www.themoviedb.org/" target="_blank"> TMDB </a>, 
            <a className="italic hover:underline text-crimson" href="https://letterboxd.com/" target="_blank"> Letterboxd</a> & generated by 
            <a className="italic hover:underline text-crimson" href="https://gemini.google.com/app" target="_blank"> Gemini</a>.
            </p>
            <p>Most imagery sourced from <a className="italic hover:underline text-crimson" href="https://unsplash.com/" target="_blank"> Unsplash</a>
 , whilst the remainder is taken by <a className="italic hover:underline text-crimson" href="#">@sonicakes</a> & feature the author herself and/or her dog.
 </p>
        </div>
      </div> );
}
 
export default MainFooter ;  
  
